[build]
type = "docker"

[deploy]
type = "web"
run_command = "uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1"

[[deploy.ports]]
port = 8000
protocol = "http"

[deploy.env]
# These will be set in Koyeb dashboard
# DATABASE_URL = "postgresql://..."
# REDIS_URL = "redis://..."
# SECRET_KEY = "..."
# TWILIO_ACCOUNT_SID = "..."
# TWILIO_AUTH_TOKEN = "..."
# TWILIO_PHONE_NUMBER = "..."

[deploy.health_check]
path = "/health"
port = 8000
initial_delay_seconds = 30
period_seconds = 10
timeout_seconds = 5
failure_threshold = 3

[deploy.resources]
memory = "512Mi"
cpu = "0.5"

[deploy.scaling]
min = 1
max = 3