server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: sales-engagement-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: sales-engagement-app
          __path__: /app/logs/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: asctime
            level: levelname
            logger: name
            message: message
            correlation_id: correlation_id
            tenant_id: tenant_id
            user_id: user_id
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05,000'
      - labels:
          level:
          logger:
          correlation_id:
          tenant_id:
          user_id:

  - job_name: sales-engagement-audit
    static_configs:
      - targets:
          - localhost
        labels:
          job: sales-engagement-audit
          __path__: /app/logs/audit.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: asctime
            action: action
            resource_type: resource_type
            resource_id: resource_id
            user_id: user_id
            tenant_id: tenant_id
            ip_address: ip_address
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05,000'
      - labels:
          action:
          resource_type:
          tenant_id:
          user_id:

  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system-logs
          __path__: /var/log/*.log